// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD67onmXmyiXaA-vyweUmjM-RIVJ6nXjQ',
    appId: '1:201259254878:web:0dd5bf55e945a3dee6a0cf',
    messagingSenderId: '201259254878',
    projectId: 'micro-rituals',
    authDomain: 'micro-rituals.firebaseapp.com',
    storageBucket: 'micro-rituals.firebasestorage.app',
    measurementId: 'G-GWVFH0PZNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6KB2SedflqD0PTPHi2dUHCbowaMj455A',
    appId: '1:201259254878:android:657d5fadeee43129e6a0cf',
    messagingSenderId: '201259254878',
    projectId: 'micro-rituals',
    storageBucket: 'micro-rituals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtzb8fe4Glmt3oqi6pJbqV4Prhkb70Ecc',
    appId: '1:201259254878:ios:e0c3ad01f13c84bce6a0cf',
    messagingSenderId: '201259254878',
    projectId: 'micro-rituals',
    storageBucket: 'micro-rituals.firebasestorage.app',
    iosBundleId: 'com.calmtech.dailyMicroRituals',
  );
}
